export * from './lib/adapters/primary/components/product-list.component-module';
export * from './lib/adapters/secondary/services/firebase-product.service-module';
export * from './lib/adapters/primary/components/product-detail.component-module'
export * from './lib/adapters/secondary/storages/in-memory-product.storage-module';
export * from './lib/adapters/primary/resolvers/product.resolver';
export * from './lib/adapters/primary/resolvers/product.resolver-module';
export * from './lib/adapters/primary/components/cart.component-module';
export * from './lib/adapters/primary/components/shop-description.component-module';
export * from './lib/adapters/primary/components/woman.component-module';
export * from './lib/adapters/primary/components/man.component-module';
